export interface Twister {
  id: string;
  text: string;
  sound: string;
  difficulty: 'easy' | 'medium' | 'hard' | 'very-hard';
}

export const twisters: Twister[] = [
  { id: '001', text: 'She sells seashells by the seashore. The shells she sells are seashells, I\'m sure. So if she sells shells on the seashore, I\'m sure she sells seashore shells.', sound: '/s/', difficulty: 'medium' },
  { id: '002', text: 'Sally sells seashells by the seashore.', sound: '/s/', difficulty: 'easy' },
  { id: '003', text: 'I saw Susie sitting in a shoeshine shop. Where she shines she sits, and where she sits she shines.', sound: '/s/ + /ʃ/', difficulty: 'medium' },
  { id: '004', text: 'Six sick slick slim sycamore saplings.', sound: '/s/', difficulty: 'hard' },
  { id: '005', text: 'Six slippery snails slid slowly seaward.', sound: '/s/', difficulty: 'medium' },
  { id: '006', text: 'Sam\'s shop stocks short spotted socks.', sound: '/s/ + /ʃ/', difficulty: 'medium' },
  { id: '007', text: 'Miss Smith\'s fish-sauce shop seldom sells shellfish.', sound: '/s/ + /ʃ/', difficulty: 'hard' },
  { id: '008', text: 'Sarah saw a shot-silk sash shop full of shot-silk sashes as the sunshine shone on the side of the shot-silk sash shop.', sound: '/s/ + /ʃ/', difficulty: 'very-hard' },
  { id: '009', text: 'Six sticky skeletons.', sound: '/s/', difficulty: 'easy' },
  { id: '010', text: 'Sister Suzie sewing shirts for soldiers.', sound: '/s/ + /ʃ/', difficulty: 'medium' },
  { id: '011', text: 'Selfish shellfish.', sound: '/s/ + /ʃ/', difficulty: 'medium' },
  { id: '012', text: 'A skunk sat on a stump and thunk the stump stunk, but the stump thunk the skunk stunk.', sound: '/s/ + /θ/', difficulty: 'hard' },
  { id: '013', text: 'I slit the sheet, the sheet I slit, and on the slitted sheet I sit.', sound: '/s/ + /ʃ/', difficulty: 'hard' },
  { id: '014', text: 'The seething sea ceaseth and thus the seething sea sufficeth us.', sound: '/s/ + /θ/', difficulty: 'very-hard' },
  { id: '015', text: 'Six shimmering sharks sharply striking shins.', sound: '/s/ + /ʃ/', difficulty: 'hard' },

  { id: '016', text: 'She sees cheese.', sound: '/ʃ/ + /tʃ/', difficulty: 'easy' },
  { id: '017', text: 'Shy Shelly says she shall sew sheets.', sound: '/ʃ/', difficulty: 'medium' },
  { id: '018', text: 'Surely Sylvia swims! shrieked Sammy, surprised. Someone should show Sylvia some strokes so she shall not sink.', sound: '/ʃ/ + /s/', difficulty: 'hard' },
  { id: '019', text: 'The sushi chef.', sound: '/ʃ/', difficulty: 'easy' },
  { id: '020', text: 'Cheap ship trip.', sound: '/tʃ/ + /ʃ/', difficulty: 'medium' },
  { id: '021', text: 'Pre-shrunk silk shirts.', sound: '/ʃ/', difficulty: 'hard' },
  { id: '022', text: 'If a dog chews shoes, whose shoes does he choose?', sound: '/ʃ/ vs /tʃ/', difficulty: 'medium' },
  { id: '023', text: 'I wish to wash my Irish wristwatch.', sound: '/ʃ/ + /r/', difficulty: 'hard' },
  { id: '024', text: 'A short, sharp shock from a cheap and chippy chopper.', sound: '/ʃ/ + /tʃ/', difficulty: 'hard' },

  { id: '025', text: 'Peter Piper picked a peck of pickled peppers. A peck of pickled peppers Peter Piper picked. If Peter Piper picked a peck of pickled peppers, where\'s the peck of pickled peppers Peter Piper picked?', sound: '/p/', difficulty: 'medium' },
  { id: '026', text: 'Betty Botter bought some butter, but, she said, the butter\'s bitter; if I put it in my batter, it will make my batter bitter, but a bit of better butter will make my batter better. So she bought a bit of butter, better than her bitter butter, and she put it in her batter, and her batter was not bitter.', sound: '/b/ + /t/', difficulty: 'hard' },
  { id: '027', text: 'A big black bear sat on a big black rug.', sound: '/b/', difficulty: 'easy' },
  { id: '028', text: 'A big black bug bit a big black bear, made the big black bear bleed blood.', sound: '/b/', difficulty: 'medium' },
  { id: '029', text: 'Big black bugs bleed blue-black blood but baby black bugs bleed blue blood.', sound: '/b/', difficulty: 'hard' },
  { id: '030', text: 'Black back bat.', sound: '/b/', difficulty: 'easy' },
  { id: '031', text: 'Pretty Kitty Creighton had a cotton batten cat. The cotton batten cat was bitten by a rat. The kitten that was bitten had a button for an eye, and biting off the button made the cotton batten fly.', sound: '/k/ + /t/', difficulty: 'hard' },
  { id: '032', text: 'Rubber baby buggy bumpers.', sound: '/b/', difficulty: 'medium' },
  { id: '033', text: 'A bloke\'s back bike brake block broke.', sound: '/b/ + /k/', difficulty: 'very-hard' },
  { id: '034', text: 'Bobby bought bright blue balloons by the big brown barn.', sound: '/b/', difficulty: 'easy' },
  { id: '035', text: 'Pad kid poured curd pulled cod.', sound: '/p/ + /k/ + /d/', difficulty: 'very-hard' },

  { id: '036', text: 'Two tried and true tridents.', sound: '/t/ + /r/', difficulty: 'medium' },
  { id: '037', text: 'Tom threw Tim three thumbtacks.', sound: '/t/ + /θ/', difficulty: 'medium' },
  { id: '038', text: 'He threw three free throws.', sound: '/θ/ + /r/', difficulty: 'medium' },
  { id: '039', text: 'Eddie edited it.', sound: '/d/ + /t/', difficulty: 'easy' },
  { id: '040', text: 'Ed had edited it.', sound: '/d/ + /t/', difficulty: 'medium' },
  { id: '041', text: 'Fred fed Ted bread, and Ted fed Fred bread.', sound: '/d/ + /f/', difficulty: 'easy' },
  { id: '042', text: 'A proper copper coffee pot.', sound: '/p/ + /k/', difficulty: 'hard' },
  { id: '043', text: 'Daring dragons dance down dusty dark dungeons.', sound: '/d/', difficulty: 'medium' },
  { id: '044', text: 'Twelve twins twirled twelve twigs.', sound: '/tw/', difficulty: 'hard' },
  { id: '045', text: 'To begin to toboggan first buy a toboggan, but don\'t buy too big a toboggan. Too big a toboggan is too big a toboggan to buy to begin to toboggan.', sound: '/t/ + /b/', difficulty: 'very-hard' },
  { id: '046', text: 'A tutor who tooted the flute tried to tutor two tooters to toot. Said the two to their tutor, "Is it harder to toot or to tutor two tooters to toot?"', sound: '/t/', difficulty: 'hard' },

  { id: '047', text: 'Red lorry, yellow lorry.', sound: '/r/ + /l/', difficulty: 'hard' },
  { id: '048', text: 'Red leather, yellow leather.', sound: '/r/ + /l/', difficulty: 'hard' },
  { id: '049', text: 'Around the rugged rocks the ragged rascals ran.', sound: '/r/', difficulty: 'hard' },
  { id: '050', text: 'Rolling red wagons.', sound: '/r/', difficulty: 'medium' },
  { id: '051', text: 'Truly rural.', sound: '/r/ + /l/', difficulty: 'hard' },
  { id: '052', text: 'Rural juror.', sound: '/r/', difficulty: 'hard' },
  { id: '053', text: 'A loyal warrior will rarely worry why we rule.', sound: '/r/ + /w/', difficulty: 'hard' },
  { id: '054', text: 'Real rock wall, real rock wall, real rock wall.', sound: '/r/ + /l/', difficulty: 'hard' },
  { id: '055', text: 'Reading bells ring rapidly and reeds rustle round rivers.', sound: '/r/', difficulty: 'medium' },

  { id: '056', text: 'Lesser leather never weathered wetter weather better.', sound: '/l/ + /ð/', difficulty: 'very-hard' },
  { id: '057', text: 'Lovely lemon liniment.', sound: '/l/', difficulty: 'medium' },
  { id: '058', text: 'Lily ladles little Letty\'s lentil soup.', sound: '/l/', difficulty: 'hard' },
  { id: '059', text: 'Eleven benevolent elephants.', sound: '/l/', difficulty: 'hard' },
  { id: '060', text: 'Larry sent the latter a letter later.', sound: '/l/ + /t/', difficulty: 'medium' },
  { id: '061', text: 'Listen to the local yokel yodel.', sound: '/l/', difficulty: 'medium' },
  { id: '062', text: 'I want the luxurious, lemon-colored limousine.', sound: '/l/', difficulty: 'medium' },

  { id: '063', text: 'Really leery, rarely Larry.', sound: '/r/ + /l/', difficulty: 'hard' },
  { id: '064', text: 'The Leith police dismisseth thee, the Leith police dismisseth us.', sound: '/l/ + /θ/', difficulty: 'very-hard' },

  { id: '065', text: 'The thirty-three thieves thought that they thrilled the throne throughout Thursday.', sound: '/θ/', difficulty: 'very-hard' },
  { id: '066', text: 'The sixth sick sheikh\'s sixth sheep\'s sick.', sound: '/ʃ/ + /θ/', difficulty: 'very-hard' },
  { id: '067', text: 'I thought I thought of thinking of thanking you.', sound: '/θ/', difficulty: 'hard' },
  { id: '068', text: 'Thirty-three thirsty, thundering thoroughbreds thumped Mr. Thurber on Thursday.', sound: '/θ/', difficulty: 'very-hard' },
  { id: '069', text: 'Three free throws.', sound: '/θ/ + /r/', difficulty: 'easy' },
  { id: '070', text: 'These thousand thinkers thought thoughtfully.', sound: '/θ/ + /ð/', difficulty: 'hard' },
  { id: '071', text: 'Whether the weather is cold or whether the weather is hot, we\'ll weather the weather, whatever the weather, whether we like it or not.', sound: '/w/ + /ð/', difficulty: 'hard' },
  { id: '072', text: 'Both thieving brothers thoughtfully threw their teeth through the thousandth threshold.', sound: '/θ/ + /ð/', difficulty: 'very-hard' },

  { id: '073', text: 'How much wood would a woodchuck chuck if a woodchuck could chuck wood? He would chuck, he would, as much as he could, and chuck as much wood as a woodchuck would if a woodchuck could chuck wood.', sound: '/w/ + /tʃ/', difficulty: 'hard' },
  { id: '074', text: 'Which witch is which?', sound: '/w/ + /tʃ/', difficulty: 'easy' },
  { id: '075', text: 'Which wristwatches are Swiss wristwatches?', sound: '/w/ + /r/', difficulty: 'hard' },
  { id: '076', text: 'Wayne went to Wales to watch walruses.', sound: '/w/', difficulty: 'medium' },
  { id: '077', text: 'Willie\'s really weary.', sound: '/w/ + /r/', difficulty: 'easy' },
  { id: '078', text: 'If two witches would watch two watches, which witch would watch which watch?', sound: '/w/ + /tʃ/', difficulty: 'very-hard' },
  { id: '079', text: 'We surely shall see the sun shine soon.', sound: '/w/ + /ʃ/ + /s/', difficulty: 'medium' },
  { id: '080', text: 'Vincent vowed vengeance very vehemently.', sound: '/v/', difficulty: 'hard' },
  { id: '081', text: 'The vacant van violated the vivid violet vase.', sound: '/v/', difficulty: 'hard' },

  { id: '082', text: 'Four fine fresh fish for you.', sound: '/f/', difficulty: 'medium' },
  { id: '083', text: 'Fresh fried fish, fish fresh fried, fried fish fresh, fish fried fresh.', sound: '/f/', difficulty: 'hard' },
  { id: '084', text: 'Friendly Frank flips fine flapjacks.', sound: '/f/ + /fl/', difficulty: 'hard' },
  { id: '085', text: 'Freshly fried fresh flesh.', sound: '/f/ + /fr/', difficulty: 'very-hard' },
  { id: '086', text: 'A flea and a fly flew up in a flue. Said the flea, "Let us fly!" Said the fly, "Let us flee!" So they flew through a flaw in the flue.', sound: '/f/ + /fl/', difficulty: 'hard' },
  { id: '087', text: 'Of all the felt I ever felt, I never felt a piece of felt which felt as fine as that felt felt.', sound: '/f/', difficulty: 'hard' },

  { id: '088', text: 'How can a clam cram in a clean cream can?', sound: '/k/ + /kl/ + /kr/', difficulty: 'medium' },
  { id: '089', text: 'How many cookies could a good cook cook if a good cook could cook cookies? A good cook could cook as many cookies as a good cook who could cook cookies.', sound: '/k/', difficulty: 'hard' },
  { id: '090', text: 'Can you can a can as a canner can can a can?', sound: '/k/', difficulty: 'hard' },
  { id: '091', text: 'Cooks cook cupcakes quickly.', sound: '/k/', difficulty: 'medium' },
  { id: '092', text: 'Quick kiss. Quicker kiss.', sound: '/k/', difficulty: 'medium' },
  { id: '093', text: 'Six sick hicks nick six slick bricks with picks and sticks.', sound: '/k/ + /s/', difficulty: 'very-hard' },
  { id: '094', text: 'Greek grapes.', sound: '/g/ + /gr/', difficulty: 'medium' },
  { id: '095', text: 'Gertie\'s great-grandma grew aghast at Gertie\'s grammar.', sound: '/g/ + /gr/', difficulty: 'hard' },
  { id: '096', text: 'Green glass globes glow greenly.', sound: '/g/ + /gl/', difficulty: 'hard' },
  { id: '097', text: 'Three gray geese in the green grass grazing. Gray were the geese and green was the grass.', sound: '/g/ + /gr/', difficulty: 'hard' },
  { id: '098', text: 'Good blood, bad blood.', sound: '/b/ + /d/', difficulty: 'hard' },

  { id: '099', text: 'A cheeky cheetah chuckled cheerfully.', sound: '/tʃ/', difficulty: 'medium' },
  { id: '100', text: 'Chop shops stock chops.', sound: '/tʃ/ + /ʃ/', difficulty: 'hard' },
  { id: '101', text: 'Mrs. Rich had lunch at the Finnish restaurant on Church Street.', sound: '/tʃ/ vs /ʃ/', difficulty: 'hard' },

  { id: '102', text: 'The judge liked fudge and he kept it in the fridge.', sound: '/dʒ/', difficulty: 'medium' },
  { id: '103', text: 'Jolly Jack and joyful Jill jumping down the jagged hill.', sound: '/dʒ/', difficulty: 'easy' },
  { id: '104', text: 'Jean, Joan, George and Gerald judged generally.', sound: '/dʒ/', difficulty: 'hard' },
  { id: '105', text: 'It was a joy for Jack and George, the German boys, to cross the large bridge before entering the village.', sound: '/dʒ/', difficulty: 'hard' },

  { id: '106', text: 'Zebra zig and zebra zag.', sound: '/z/', difficulty: 'easy' },
  { id: '107', text: 'Fuzzy Wuzzy was a bear. Fuzzy Wuzzy had no hair. Fuzzy Wuzzy wasn\'t fuzzy, was he?', sound: '/z/', difficulty: 'medium' },
  { id: '108', text: 'The buzzing bumblebee buzzed by Bob.', sound: '/z/ + /b/', difficulty: 'medium' },

  { id: '109', text: 'Unique New York.', sound: '/juː/ + /n/ + /k/', difficulty: 'hard' },
  { id: '110', text: 'Near an ear, a nearer ear, a nearly eerie ear.', sound: '/ɪər/', difficulty: 'hard' },
  { id: '111', text: 'The rain in Spain stays mainly on the plain.', sound: '/eɪ/', difficulty: 'easy' },
  { id: '112', text: 'I scream, you scream, we all scream for ice cream.', sound: '/aɪ/ + /s/', difficulty: 'easy' },
  { id: '113', text: 'Any noise annoys an oyster, but a noisy noise annoys an oyster more.', sound: '/ɔɪ/', difficulty: 'hard' },
  { id: '114', text: 'The four fur shirts were too short for the walk to work, so I burned them on the lawn where bored birds are born.', sound: '/ɔː/ vs /ɜː/', difficulty: 'very-hard' },

  { id: '115', text: 'Sheena leads, Sheila needs.', sound: '/ʃ/ + /n/ + /l/', difficulty: 'hard' },
  { id: '116', text: 'A proper cup of coffee from a proper copper coffee pot.', sound: '/p/ + /k/', difficulty: 'very-hard' },
  { id: '117', text: 'Ned Nott was shot and Sam Shott was not. So it is better to be Shott than Nott. Some say Nott was not shot. But Shott says he shot Nott. Either the shot Shott shot at Nott was not shot, or Nott was shot.', sound: '/n/ + /ʃ/ + /t/', difficulty: 'very-hard' },
  { id: '118', text: 'Shep Schwab shopped at Scott\'s Schnapps shop; one shot of Scott\'s Schnapps stopped Schwab\'s watch.', sound: '/ʃ/ + /sk/ + /sw/', difficulty: 'very-hard' },
  { id: '119', text: 'Stupid superstition.', sound: '/s/ + /st/', difficulty: 'medium' },
  { id: '120', text: 'Thin sticks, thick bricks.', sound: '/θ/ + /st/ + /br/', difficulty: 'hard' },
  { id: '121', text: 'Snap, crackle, pop.', sound: '/s/ + /k/ + /p/', difficulty: 'easy' },
  { id: '122', text: 'Flash message.', sound: '/fl/ + /ʃ/', difficulty: 'medium' },
  { id: '123', text: 'Roberta ran rings around the Roman ruins.', sound: '/r/', difficulty: 'hard' },
  { id: '124', text: 'Amidst the mists and coldest frosts, with stoutest wrists and loudest boasts, he thrusts his fist against the posts and still insists he sees the ghosts.', sound: '/st/ + /s/', difficulty: 'very-hard' },
  { id: '125', text: 'A pleasant place to place a plaice is a place where a plaice is pleased to be placed.', sound: '/pl/ + /s/', difficulty: 'very-hard' },
  { id: '126', text: 'To sit in solemn silence on a dull dark dock, in a pestilential prison with a lifelong lock, awaiting the sensation of a short, sharp shock from a cheap and chippy chopper with a big black block.', sound: '/s/ + /tʃ/ + /ʃ/', difficulty: 'very-hard' },
];
